ipv6: true

rules:
  # Geph
  - PROCESS-NAME,libgeph.so,DIRECT
  - PROCESS-NAME,geph4-client,DIRECT
  - PROCESS-NAME,geph4-client.exe,DIRECT

  # Private address
  - RULE-SET,private,DIRECT
  - RULE-SET,lancidr,DIRECT,no-resolve
  - GEOIP,LAN,DIRECT,no-resolve

  # AD/Block
  - RULE-SET,reject,REJECT
  - RULE-SET,custom-reject,REJECT
  - SCRIPT,bilibili-p2p,REJECT,no-resolve
  - SCRIPT,quic,REJECT,no-resolve

  # Custom
  - RULE-SET,custom-proxy,PROXY
  - RULE-SET,custom-direct,DIRECT
  - PROCESS-NAME,IDMan.exe,Downloader
  - PROCESS-NAME,qbittorrent.exe,Downloader
  - RULE-SET,applications,DIRECT
  - DOMAIN-SUFFIX,bing.com,Bing
  - DOMAIN-SUFFIX,bingapis.com,Bing
  # - RULE-SET,bilibili,Bilibili,no-resolve
  # - SCRIPT,genshin-udp,Game-UDP,no-resolve
  # - DOMAIN-SUFFIX,openai.com,OpenAI

  # China CDN/Direct/Game
  - RULE-SET,ip-attribution-reject,REJECT,no-resolve
  - RULE-SET,ip-attribution-direct,DIRECT,no-resolve
  - RULE-SET,ip-attribution-proxy,IPAttribution,no-resolve
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  # Not China
  - RULE-SET,proxy,PROXY
  - RULE-SET,telegramcidr,PROXY,no-resolve
  # China
  - RULE-SET,direct,DIRECT
  - RULE-SET,cncidr,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  # Other
  - MATCH,MATCH

script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443 and (geoip(resolve_ip(host)) != 'CN' or geoip(dst_ip) != 'CN')
    # bilibili-p2p: network == 'udp' and host.endswith('bilibili.com')
    bilibili-p2p: network == 'udp' and match_provider('bilibili')
    # genshin-asia-udp: network == 'udp' and in_cidr(dst_ip,'8.211.128.0/18')
    genshin-udp: network == 'udp' and resolve_process_name() == 'GenshinImpact.exe'

proxy-groups:
  - name: Fallback
    type: fallback
    proxies:
      - local_9909
      - local_9901
      - local_9902
      - local_9903
      - local_9904
      # - DIRECT
    url: "http://captive.apple.com/generate_204"
    interval: 300
  - name: PROXY
    type: select
    proxies:
      - Fallback
      - DIRECT
      - local_9909
      - local_9901
      - local_9902
      - local_9903
      - local_9904
      - local_2080
      - local_2090
      - local_9900

  # Rule
  - name: Bing
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: OpenAI
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: GoogleFCM
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: Bilibili
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: Downloader
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: IPAttribution
    type: select
    proxies:
      - PROXY
      - DIRECT
      - REJECT
  # - name: Game
  #   type: select
  #   proxies:
  #     - PROXY
  #     - DIRECT
  # - name: Game-UDP
  #   type: select
  #   proxies:
  #     - DIRECT
  #     - PROXY
  - name: MATCH
    type: select
    proxies:
      - PROXY
      - DIRECT


dns:
  enable: true
  # ipv6: true
  listen: :1053
  default-nameserver:
    - 8.8.8.8
    - 223.5.5.5
  nameserver:
    - tls://dot.pub
    - tls://dns.alidns.com
  fallback:
    - tcp://dns.google
    - tcp://cloudflare-dns.com
  # use-hosts: true
  # enhanced-mode: fake-ip
  # enhanced-mode: normal
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - Mijia Cloud
    - "+.dns.google"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.apple.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.returnyoutubedislikeapi.com"
      - "+.googleapis.com"
      - "+.gvt1.com"
      - "+.gvt2.com"
      - "+.citibankonline.com"
      - "+.citi.com"
      - "+.booking.com"
      - "+.googlesyndication.com"
      - "+.googletagmanager.com"
      - "+.pki.goog"
      - "+.thinkwithgoogle.com"
      - "+.gstatic.com"
      - "+.cloudfront.net"
      - "+.obsidian.md"
      - "+.doubleclick.net"
      - "+.3gppnetwork.org"

# Premium
tun:
  enable: false
  stack: system
  auto-route: true
  auto-redir: true # Linux?
  # strict_route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

proxies:
  - name: local_9909
    type: socks5
    server: 127.0.0.1
    port: 9909
  - name: local_9901
    type: socks5
    server: 127.0.0.1
    port: 9901
  - name: local_9902
    type: socks5
    server: 127.0.0.1
    port: 9902
  - name: local_9903
    type: socks5
    server: 127.0.0.1
    port: 9903
  - name: local_9904
    type: socks5
    server: 127.0.0.1
    port: 9904
  - name: local_2090
    type: socks5
    server: 127.0.0.1
    port: 2090
  - name: local_2080
    type: socks5
    server: 127.0.0.1
    port: 2080
  - name: local_9900
    type: socks5
    server: 127.0.0.1
    port: 9900

mixed-port: 7890
allow-lan: true
mode: rule
log-level: debug
external-controller: 0.0.0.0:9090
profile:
  store-selected: false
  store-fake-ip: true

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
  ip-attribution-direct:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider-direct.yaml"
    path: ./ruleset/ip-attribution-direct.yaml
    interval: 86400
  ip-attribution-reject:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider-reject.yaml"
    path: ./ruleset/ip-attribution-reject.yaml
    interval: 86400
  ip-attribution-proxy:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider-proxy.yaml"
    path: ./ruleset/ip-attribution-proxy.yaml
    interval: 86400
  # bilibili:
  #   type: http
  #   behavior: classical
  #   url: "https://ghproxy.com/https:/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
  #   path: ./ruleset/bilibili.yaml
  #   interval: 86400
  custom-proxy:
    type: file
    behavior: classical
    path: ./ruleset/custom-proxy.yaml
    interval: 86400
  custom-direct:
    type: file
    behavior: classical
    path: ./ruleset/custom-direct.yaml
    interval: 86400
  custom-reject:
    type: file
    behavior: classical
    path: ./ruleset/custom-reject.yaml
    interval: 86400
