mixed-port: 7890
allow-lan: true
external-controller: :9090
ipv6: false
profile:
  store-selected: true
hosts:
  'ntp.msn.cn': '0.0.0.0'

script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
    # bilibili-p2p: network == 'udp' and host.endswith('bilibili.com')
    bilibili-p2p: network == 'udp' and match_provider('bilibili')
    # genshin-asia-udp: network == 'udp' and in_cidr(dst_ip,'8.211.128.0/18')
    genshin-udp: network == 'udp' and resolve_process_name() == 'GenshinImpact.exe'

rules:
  # Geph
  - PROCESS-NAME,libgeph.so,DIRECT
  - PROCESS-NAME,geph4-client,DIRECT
  - PROCESS-NAME,geph4-client.exe,DIRECT

  # Private address
  - RULE-SET,private,DIRECT
  - RULE-SET,lancidr,DIRECT
  - GEOIP,LAN,DIRECT,no-resolve

  # AD/Block
  - RULE-SET,reject,REJECT
  - DOMAIN,ntp.msn.cn,REJECT
  - SCRIPT,bilibili-p2p,REJECT
  # - SCRIPT,quic,REJECT

  # App
  - PROCESS-NAME,IDMan.exe,Downloader
  - PROCESS-NAME,qbittorrent.exe,Downloader
  # - PROCESS-NAME,GenshinImpact.exe,Games
  - PROCESS-NAME,SCPSL.exe,Games
  - PROCESS-NAME,csgo.exe,Games
  - RULE-SET,applications,DIRECT

  # Web site
  - DOMAIN-SUFFIX,dockerproxy.com,DIRECT
  - DOMAIN-SUFFIX,metacubex.one,DIRECT
  - DOMAIN-SUFFIX,winos.me,DIRECT
  - DOMAIN-SUFFIX,kinh.cc,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,clash.razord.top,DIRECT

  # China CDN/Direct/Game
  - RULE-SET,ip-attribution-reject,REJECT
  - RULE-SET,ip-attribution-direct,DIRECT
  - RULE-SET,ip-attribution-proxy,ip-attribution
  - RULE-SET,bilibili,bilibili
  # - SCRIPT,genshin-asia-udp,Games
  - SCRIPT,genshin-udp,Games
  # - IP-CIDR,8.211.128.0/18,Games # Genshin Asia
  # - IP-CIDR,47.74.0.0/18,Games # Genshin Asia
  - DOMAIN,dispatchosglobal.yuanshen.com,Games # Genshin global
  - DOMAIN-SUFFIX,openai.com,OpenAI
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT

  # Not China
  - RULE-SET,proxy,PROXY
  - RULE-SET,telegramcidr,PROXY

  # China
  - RULE-SET,direct,DIRECT
  - RULE-SET,cncidr,DIRECT
  - GEOIP,CN,DIRECT,no-resolve

  # Other
  - MATCH,MATCH

proxies:
  - name: local_9909
    type: socks5
    server: 127.0.0.1
    port: 9909
  - name: local_9901
    type: socks5
    server: 127.0.0.1
    port: 9901
  - name: local_9902
    type: socks5
    server: 127.0.0.1
    port: 9902
  - name: local_9903
    type: socks5
    server: 127.0.0.1
    port: 9903
  - name: local_9904
    type: socks5
    server: 127.0.0.1
    port: 9904

  - name: remote_9909
    type: socks5
    server: 192.168.1.1
    port: 9909
  - name: remote_9900
    type: socks5
    server: 192.168.1.1
    port: 9900
    udp: true
  - name: remote_9901
    type: socks5
    server: 192.168.1.1
    port: 9901
  - name: remote_9902
    type: socks5
    server: 192.168.1.1
    port: 9902
  - name: remote_9903
    type: socks5
    server: 192.168.1.1
    port: 9903
  - name: remote_9904
    type: socks5
    server: 192.168.1.1
    port: 9904


proxy-groups:
  - name: fallback
    type: fallback
    proxies:
      - local_9909
      - local_9901
      - local_9902
      - local_9903
      - local_9904
      - remote_9909
      - remote_9901
      - remote_9902
      - remote_9903
      - remote_9904
      - remote_9900
      - DIRECT
    url: "http://www.v2ex.com/generate_204"
    interval: 300
  - name: PROXY
    type: select
    proxies:
      - fallback
      - DIRECT
      - local_9909
      - local_9901
      - local_9902
      - local_9903
      - local_9904
      - remote_9909
      - remote_9901
      - remote_9902
      - remote_9903
      - remote_9904
      - remote_9900

  # Rule
  - name: OpenAI
    type: select
    proxies:
      - DIRECT
      - PASS
      - PROXY
  - name: GoogleFCM
    type: select
    proxies:
      - DIRECT
      - PASS
      - PROXY
  - name: bilibili
    type: select
    proxies:
      - PASS
      - DIRECT
      - PROXY
  - name: Downloader
    type: select
    proxies:
      - PASS
      - DIRECT
      - PROXY
  - name: ip-attribution
    type: select
    proxies:
      - PASS
      - PROXY
      - DIRECT
      - REJECT
  - name: Games
    type: select
    proxies:
      - PASS
      - remote_9900
      - DIRECT
      - PROXY

  - name: MATCH
    type: select
    proxies:
      - PROXY
      - DIRECT

  # Meta compatible
  - name: PASS
    type: select
    proxies:
      - DIRECT
      - PROXY

dns:
  enable: true
  ipv6: false
  listen: :53
  default-nameserver:
    - 8.8.8.8
    - 223.5.5.5
  enhanced-mode: redir-host 
  use-hosts: true
  nameserver:
    - tls://dot.pub:853
    - tls://dns.alidns.com:853
  fallback:
  - 127.0.0.1:15353
  - 127.0.0.1:9921
  - 127.0.0.1:9922
  - 127.0.0.1:9923
  - 127.0.0.1:9924
  - 192.168.1.1:15353
  - 192.168.1.1:9921
  - 192.168.1.1:9922
  - 192.168.1.1:9923
  - 192.168.1.1:9924
  - https://dns.google/dns-query
  - https://dns.twnic.tw/dns-query
  - https://cloudflare-dns.com/dns-query

  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
  - tls://dot.tiar.app
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com

# Premium
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redir: true # Linux?
  strict_route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  ip-attribution-direct:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/lwd-temp/anti-ip-attribution@main/generated/rule-provider-direct.yaml"
    path: ./ruleset/ip-attribution-direct.yaml
    interval: 86400
  ip-attribution-reject:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/lwd-temp/anti-ip-attribution@main/generated/rule-provider-reject.yaml"
    path: ./ruleset/ip-attribution-reject.yaml
    interval: 86400
  ip-attribution-proxy:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/lwd-temp/anti-ip-attribution@main/generated/rule-provider-proxy.yaml"
    path: ./ruleset/ip-attribution-proxy.yaml
    interval: 86400

  bilibili:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./ruleset/bilibili.yaml
    interval: 86400
