rules:
  # Geph
  - PROCESS-NAME,geph4-client.exe,DIRECT

  # AD/Block
  - RULE-SET,custom-reject,REJECT
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,win-spy,REJECT
  # - GEOSITE,win-extra,REJECT
  - AND,((OR,((GEOSITE,bilibili),(GEOSITE,douyu))),(NETWORK,UDP,no-resolve)),REJECT
  # - AND,((NETWORK,UDP,no-resolve),(DST-PORT,443)),REJECT
  - AND,((AND,((NETWORK,UDP,no-resolve),(DST-PORT,443))),(OR,(NOT,((GEOIP,cn,no-resolve))),(GEOSITE,geolocation-!cn))),REJECT

  # Custom
  - RULE-SET,custom-proxy,PROXY
  - RULE-SET,custom-direct,DIRECT
  - RULE-SET,applications,DIRECT
  - GEOSITE,bing,Bing
  - GEOSITE,googlefcm,GoogleFCM
  # - GEOSITE,bilibili,Bilibili
  # - AND,((PROCESS-NAME,GenshinImpact.exe),(NETWORK,TCP)),PROXY
  # - SUB-RULE,(PROCESS-NAME,GenshinImpact.exe),genshin

  # China CDN/Direct
  - RULE-SET,ip-attribution-reject,REJECT,no-resolve
  - RULE-SET,ip-attribution-direct,DIRECT,no-resolve
  - RULE-SET,ip-attribution-proxy,IPAttribution,no-resolve
  # - AND,((GEOSITE,bilibili,Bilibili),(RULE-SET,ip-attribution-proxy,no-resolve)),IPAttribution
  # - GEOSITE,apple-cn,DIRECT
  # - GEOSITE,google-cn,DIRECT
  - GEOSITE,tld-cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn@cn,DIRECT

  # Not China
  - GEOSITE,geolocation-cn@!cn,PROXY
  - GEOSITE,geolocation-!cn,PROXY
  # - GEOSITE,cn@!cn,PROXY

  # China
  - GEOSITE,geolocation-cn,DIRECT
  # - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT,no-resolve
  # Private address
  - GEOSITE,private,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  # Other
  - MATCH,MATCH

sub-rules:
  global-proxy:
    - MATCH,WARP
  # genshin:
  #   # - IP-CIDR,8.211.128.0/18,Games,udp # Genshin Asia
  #   # - IP-CIDR,47.74.0.0/18,Games,udp # Genshin Asia
  #   - NETWORK,UDP,Games-UDP
  #   # - DOMAIN,dispatchosglobal.yuanshen.com,PROXY # Genshin global
  #   - NETWORK,TCP,PROXY

proxy-groups:
  - name: Fallback
    type: fallback
    proxies:
      - geph_1
      - geph_2
      - geph_3
      - geph_4
      - geph_default
      # - DIRECT
    url: "http://google.com/generate_204"
    interval: 300
  - name: PROXY
    type: select
    proxies:
      - Fallback
      - WARP
      - aggregator
      - geph_default
      - geph_1
      - geph_2
      - geph_3
      - geph_4
      - DIRECT
  - name: WARPOut
    type: select
    proxies:
      - DIRECT
      - Fallback
      - geph_default
      - geph_1
      - geph_2
      - geph_3
      - geph_4
  - name: aggregator
    type: url-test
    use:
      - aggregator
    url: "http://captive.apple.com/generate_204"
    interval: 300

  # Rule
  - name: Bing
    type: select
    proxies:
      - PROXY
      - PASS
      - DIRECT
  - name: GoogleFCM
    type: select
    proxies:
      - DIRECT
      - PASS
      - PROXY
  # - name: Bilibili
  #   type: select
  #   proxies:
  #     - DIRECT
  #     - PROXY
  - name: IPAttribution
    type: select
    proxies:
      - PASS
      - PROXY
      - DIRECT
  # - name: Game
  #   type: select
  #   proxies:
  #     - PROXY
  #     - PASS
  #     - DIRECT
  # - name: Games-UDP
  #   type: select
  #   proxies:
  #     - DIRECT
  #     - PROXY
  - name: MATCH
    type: select
    proxies:
      - PROXY
      - DIRECT

rule-providers:
  applications:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/releases/latest/download/applications.txt"
    path: ./provider/rule-set/applications.yaml
    interval: 86400
  ip-attribution-direct:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider-direct.yaml"
    path: ./provider/rule-set/ip-attribution-direct.yaml
    interval: 86400
  ip-attribution-reject:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider-reject.yaml"
    path: ./provider/rule-set/ip-attribution-reject.yaml
    interval: 86400
  ip-attribution-proxy:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider-proxy.yaml"
    path: ./provider/rule-set/ip-attribution-proxy.yaml
    interval: 86400
  custom-proxy:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/touhoured/files/master/clash/provider/rule-set/custom-proxy.yaml"
    path: ./provider/rule-set/custom-proxy.yaml
    interval: 86400
  custom-direct:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/touhoured/files/master/clash/provider/rule-set/custom-direct.yaml"
    path: ./provider/rule-set/custom-direct.yaml
    interval: 86400
  custom-reject:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/touhoured/files/master/clash/provider/rule-set/custom-reject.yaml"
    path: ./provider/rule-set/custom-reject.yaml
    interval: 86400
  cn:
    behavior: domain
    interval: 86400
    path: ./provider/rule-set/cn_domain.yaml
    type: http
    url: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@releases/latest/download/cn_domain.yaml"

proxy-providers:
  aggregator:
    type: http
    url: "https://ghproxy.com/https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity.yml"
    interval: 3600
    path: ./provider/proxy-set/aggregator.yaml
    health-check:
      enable: true
      interval: 300
      url: "http://captive.apple.com/generate_204"

proxies:
  - name: geph_default
    type: http
    server: 127.0.0.1
    port: 9910
  - name: geph_1
    type: http
    server: 127.0.0.1
    port: 9911
  - name: geph_2
    type: http
    server: 127.0.0.1
    port: 9912
  - name: geph_3
    type: http
    server: 127.0.0.1
    port: 9913
  - name: geph_4
    type: http
    server: 127.0.0.1
    port: 9913

  - name: "WARP"
    type: wireguard
    server: engage.cloudflareclient.com
    port: 2480
    ip: "172.16.0.2/32"
    ipv6: "2606:4700:110:8abe:359b:1b05:fda5:2ca7/128"
    private-key: "EBEM7TfbpXZ2mPv7Y4Wq/ykXOvCBIA4px5OlRqxX8Fc="
    public-key: "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
    udp: true
    # reserved: [219, 212, 139]
    mtu: 1280
    # dialer-proxy: "WARPOut"
    remote-dns-resolve: true
    dns:
      - https://dns.cloudflare.com/dns-query

dns:
  enable: false
  # ipv6: true
  listen: :1053
  default-nameserver:
    - 8.8.8.8
    - 223.5.5.5
  enhanced-mode: redir-host
  # enhanced-mode: fake-ip
  # enhanced-mode: normal
  nameserver:
    - tls://dns.pub
    - tls://dns.alidns.com
  fallback:
    - https://dns.google/dns-query&h3=false
    - https://cloudflare-dns.com/dns-query&h3=false
    - tcp://dns.google
    - tcp://cloudflare-dns.com

mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
secret: touhoured
profile:
  store-selected: true
  # store-fake-ip: true

# Meta
inbound-tfo: false # TCP Fast Open
geodata-mode: true
tcp-concurrent: false
unified-delay: false # Self deception
global-client-fingerprint: chrome
external-ui: yacd

geox-url:
  geoip: "https://ghproxy.com/https://github.com/touhoured/meta-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://ghproxy.com/https://github.com/touhoured/meta-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://ghproxy.com/https://github.com/touhoured/meta-rules-dat/releases/latest/download/Country.mmdb"
