rules:
  # Geph
  - PROCESS-NAME,libgeph.so,DIRECT
  - PROCESS-NAME,geph4-client,DIRECT
  - PROCESS-NAME,geph4-client.exe,DIRECT

  # AD/Block
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,win-spy,REJECT
  - DOMAIN,ntp.msn.cn,REJECT
  - AND,((OR,((DOMAIN-KEYWORD,bilibili),(DOMAIN-KEYWORD,douyu))),(NETWORK,UDP)),REJECT

  # Private address
  - GEOSITE,private,DIRECT
  - GEOIP,private,DIRECT,no-resolve

  # App
  - RULE-SET,applications,DIRECT
  - PROCESS-NAME,IDMan.exe,Downloader
  - PROCESS-NAME,qbittorrent.exe,Downloader
  # - PROCESS-NAME,SCPSL.exe,Game
  # - PROCESS-NAME,csgo.exe,Game

  # Web site
  - DOMAIN-SUFFIX,dockerproxy.com,DIRECT
  - DOMAIN-SUFFIX,metacubex.one,DIRECT
  - DOMAIN-SUFFIX,winos.me,DIRECT
  - DOMAIN-SUFFIX,kinh.cc,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,clash.razord.top,DIRECT

  # China CDN/Direct
  - RULE-SET,ip-attribution-reject,REJECT
  - RULE-SET,ip-attribution-direct,DIRECT
  - RULE-SET,ip-attribution-proxy,IP-Attribution
  - GEOSITE,bilibili,Bilibili
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,tld-cn,DIRECT
  - GEOSITE,googlefcm,GoogleFCM
  - GEOSITE,openai,OpenAI
  - GEOSITE,category-games@cn,DIRECT
  - SUB-RULE,(PROCESS-NAME,GenshinImpact.exe),genshin

  # Not China
  - GEOSITE,geolocation-!cn,PROXY

  # China
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT,no-resolve

  # Other
  - MATCH,MATCH

sub-rules:
  genshin:
    # - IP-CIDR,8.211.128.0/18,Games,udp # Genshin Asia
    # - IP-CIDR,47.74.0.0/18,Games,udp # Genshin Asia
    - NETWORK,UDP,Game-UDP
    - DOMAIN,dispatchosglobal.yuanshen.com,Game # Genshin global

proxy-groups:
  - name: Auto
    type: fallback
    proxies:
      - local_9909
      - local_9901
      - local_9902
      - local_9903
      - local_9904
      - remote_9909
      - remote_9901
      - remote_9902
      - remote_9903
      - remote_9904
      - remote_9900
    url: "http://www.v2ex.com/generate_204"
    interval: 300
  - name: Fallback
    type: fallback
    proxies:
      - Auto
      - DIRECT
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
  - name: UDP-Fallback
    type: fallback
    proxies:
      - remote_9900
      - DIRECT
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
  - name: PROXY
    type: select
    proxies:
      - Fallback
      - DIRECT
      - local_9909
      - local_9901
      - local_9902
      - local_9903
      - local_9904
      - remote_9909
      - remote_9901
      - remote_9902
      - remote_9903
      - remote_9904
      - remote_9900

  # Rule
  - name: OpenAI
    type: select
    proxies:
      - DIRECT
      - PASS
      - PROXY
  - name: GoogleFCM
    type: select
    proxies:
      - DIRECT
      - PASS
      - PROXY
  - name: Bilibili
    type: select
    proxies:
      - PASS
      - DIRECT
      - PROXY
  - name: Downloader
    type: select
    proxies:
      - PASS
      - DIRECT
      - PROXY
  - name: IP-Attribution
    type: select
    proxies:
      - PASS
      - PROXY
      - DIRECT
      - REJECT
  - name: Game
    type: select
    proxies:
      - PROXY
      - PASS
      - DIRECT
  - name: Game-UDP
    type: select
    proxies:
      - DIRECT
      - remote_9900
      - PASS
      - PROXY

  - name: MATCH
    type: select
    proxies:
      - PROXY
      - DIRECT

rule-providers:
  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  ip-attribution-direct:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/lwd-temp/anti-ip-attribution@main/generated/rule-provider-direct.yaml"
    path: ./ruleset/ip-attribution-direct.yaml
    interval: 86400
  ip-attribution-reject:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/lwd-temp/anti-ip-attribution@main/generated/rule-provider-reject.yaml"
    path: ./ruleset/ip-attribution-reject.yaml
    interval: 86400
  ip-attribution-proxy:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/lwd-temp/anti-ip-attribution@main/generated/rule-provider-proxy.yaml"
    path: ./ruleset/ip-attribution-proxy.yaml
    interval: 86400

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  prefer-h3: false
  default-nameserver:
    - 8.8.8.8
    - 223.5.5.5
  enhanced-mode: redir-host
  use-hosts: true
  nameserver:
    - tls://dns.pub:853
    - tls://dns.alidns.com:853
  fallback:
    # - 127.0.0.1:15353
    # - 127.0.0.1:9921
    # - 127.0.0.1:9922
    # - 127.0.0.1:9923
    # - 127.0.0.1:9924
    # - 192.168.1.1:15353
    # - 192.168.1.1:9921
    # - 192.168.1.1:9922
    # - 192.168.1.1:9923
    # - 192.168.1.1:9924
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN  # Meta # unnecessary
    geosite:  # Meta
      - gfw
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
      - msftconnecttest.com
      - msftncsi.com


# Premium
tun:
  enable: true
  stack: system
  auto-route: true
  auto-redir: true # Linux?
  strict_route: true
  auto-detect-interface: true
  dns-hijack:
    # - 0.0.0.0:53
    - any:53

# Meta
sniffer:
  enable: false
  force-dns-mapping: true
  parse-pure-ip: true
  # Whether to use sniffing results as actual access, default false
  override-destination: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
  force-domain:
    - '+.v2ex.com'
  skip-domain:
    - Mijia Cloud


proxies:
  - name: local_9909
    type: socks5
    server: 127.0.0.1
    port: 9909
  - name: local_9901
    type: socks5
    server: 127.0.0.1
    port: 9901
  - name: local_9902
    type: socks5
    server: 127.0.0.1
    port: 9902
  - name: local_9903
    type: socks5
    server: 127.0.0.1
    port: 9903
  - name: local_9904
    type: socks5
    server: 127.0.0.1
    port: 9904

  - name: remote_9909
    type: socks5
    server: 192.168.1.1
    port: 9909
  - name: remote_9900
    type: socks5
    server: 192.168.1.1
    port: 9900
    udp: true
  - name: remote_9901
    type: socks5
    server: 192.168.1.1
    port: 9901
  - name: remote_9902
    type: socks5
    server: 192.168.1.1
    port: 9902
  - name: remote_9903
    type: socks5
    server: 192.168.1.1
    port: 9903
  - name: remote_9904
    type: socks5
    server: 192.168.1.1
    port: 9904

mixed-port: 7890
allow-lan: true
mode: rule
log-level: debug
ipv6: true
external-controller: :9090
profile:
  store-selected: false
# Meta
inbound-tfo: true # TCP Fast Open
geodata-mode: true
tcp-concurrent: true
unified-delay: true # Real delay check?
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
