rules:
  # Geph
  - PROCESS-NAME,geph4-client.exe,DIRECT

  # AD/Block
  - RULE-SET,custom-reject,REJECT
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,win-spy,REJECT
  # - GEOSITE,win-extra,REJECT
  - AND,((OR,((DOMAIN-KEYWORD,bilibili),(DOMAIN-KEYWORD,douyu))),(NETWORK,UDP,no-resolve)),REJECT
  # - AND,((AND,((NETWORK,UDP,no-resolve),(DST-PORT,443))),(NOT,((GEOIP,cn,no-resolve)))),REJECT
  - AND,((NETWORK,UDP,no-resolve),(DST-PORT,443)),REJECT

  # Custom
  - RULE-SET,custom-proxy,PROXY
  - RULE-SET,custom-direct,DIRECT
  - RULE-SET,applications,DIRECT
  - GEOSITE,bing,Bing
  - GEOSITE,googlefcm,GoogleFCM
  # - GEOSITE,bilibili,Bilibili
  # - AND,((PROCESS-NAME,GenshinImpact.exe),(NETWORK,TCP)),PROXY
  # - SUB-RULE,(PROCESS-NAME,GenshinImpact.exe),genshin

  # China CDN/Direct
  - RULE-SET,ip-attribution-reject,REJECT,no-resolve
  - RULE-SET,ip-attribution-direct,DIRECT,no-resolve
  # - RULE-SET,ip-attribution-proxy,IPAttribution,no-resolve
  - AND,((GEOSITE,bilibili,Bilibili),(RULE-SET,ip-attribution-proxy,no-resolve)),IPAttribution
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,tld-cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  # - GEOSITE,geolocation-!cn@cn,DIRECT

  # Not China
  - GEOSITE,geolocation-!cn,PROXY

  # China
  - GEOSITE,cn@!cn,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOIP,CN,DIRECT,no-resolve
  # Private address
  - GEOSITE,private,DIRECT
  - GEOIP,PRIVATE,DIRECT,no-resolve
  # Other
  - MATCH,MATCH

sub-rules:
  global-proxy:
    - MATCH,WARP
  # genshin:
  #   # - IP-CIDR,8.211.128.0/18,Games,udp # Genshin Asia
  #   # - IP-CIDR,47.74.0.0/18,Games,udp # Genshin Asia
  #   - NETWORK,UDP,Games-UDP
  #   # - DOMAIN,dispatchosglobal.yuanshen.com,PROXY # Genshin global
  #   - NETWORK,TCP,PROXY

proxy-groups:
  - name: Fallback
    type: fallback
    proxies:
      - geph_1
      - geph_2
      - geph_3
      - geph_4
      - geph_default
      # - DIRECT
    url: "http://google.com/generate_204"
    interval: 300
  - name: PROXY
    type: select
    proxies:
      - Fallback
      - WARP
      - aggregator
      - geph_default
      - geph_1
      - geph_2
      - geph_3
      - geph_4
      - DIRECT
  - name: WARPOut
    type: select
    proxies:
      - DIRECT
      - Fallback
      - geph_default
      - geph_1
      - geph_2
      - geph_3
      - geph_4
  - name: aggregator
    type: url-test
    use:
      - aggregator
    url: "http://captive.apple.com/generate_204"
    interval: 300

  # Rule
  - name: Bing
    type: select
    proxies:
      - PROXY
      - PASS
      - DIRECT
  - name: GoogleFCM
    type: select
    proxies:
      - DIRECT
      - PASS
      - PROXY
  # - name: Bilibili
  #   type: select
  #   proxies:
  #     - DIRECT
  #     - PROXY
  - name: IPAttribution
    type: select
    proxies:
      - PASS
      - PROXY
      - DIRECT
  # - name: Game
  #   type: select
  #   proxies:
  #     - PROXY
  #     - PASS
  #     - DIRECT
  # - name: Games-UDP
  #   type: select
  #   proxies:
  #     - DIRECT
  #     - PROXY
  - name: MATCH
    type: select
    proxies:
      - PROXY
      - DIRECT

dns:
  enable: true
  # ipv6: true
  listen: :1053
  default-nameserver:
    - 8.8.8.8
    - 223.5.5.5
  enhanced-mode: redir-host
  # enhanced-mode: fake-ip
  # enhanced-mode: normal
  nameserver:
    - tls://dns.pub
    - tls://dns.alidns.com
  fallback:
    # - https://dns.google/dns-query&h3=false
    # - https://cloudflare-dns.com/dns-query&h3=false
    - tcp://dns.google
    - tcp://cloudflare-dns.com
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - Mijia Cloud
    - "+.dns.google"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.apple.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.returnyoutubedislikeapi.com"
      - "+.googleapis.com"
      - "+.gvt1.com"
      - "+.gvt2.com"
      - "+.citibankonline.com"
      - "+.citi.com"
      - "+.booking.com"
      - "+.googlesyndication.com"
      - "+.googletagmanager.com"
      - "+.pki.goog"
      - "+.thinkwithgoogle.com"
      - "+.gstatic.com"
      - "+.cloudfront.net"
      - "+.obsidian.md"
      - "+.doubleclick.net"
      - "+.3gppnetwork.org"

rule-providers:
  applications:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https:/raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
  ip-attribution-direct:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider-direct.yaml"
    path: ./ruleset/ip-attribution-direct.yaml
    interval: 86400
  ip-attribution-reject:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider-reject.yaml"
    path: ./ruleset/ip-attribution-reject.yaml
    interval: 86400
  ip-attribution-proxy:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider-proxy.yaml"
    path: ./ruleset/ip-attribution-proxy.yaml
    interval: 86400
  custom-proxy:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/touhoured/files/master/clash/ruleset/custom-proxy.yaml"
    path: ./ruleset/custom-proxy.yaml
    interval: 86400
  custom-direct:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/touhoured/files/master/clash/ruleset/custom-direct.yaml"
    path: ./ruleset/custom-direct.yaml
    interval: 86400
  custom-reject:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/touhoured/files/master/clash/ruleset/custom-reject.yaml"
    path: ./ruleset/custom-reject.yaml
    interval: 86400

proxy-providers:
  aggregator:
    type: http
    url: "https://ghproxy.com/https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity.yml"
    interval: 3600
    path: ./proxyset/aggregator.yaml
    health-check:
      enable: true
      interval: 300
      url: "http://captive.apple.com/generate_204"



# Premium
tun:
  enable: false
  stack: system
  auto-route: true
  strict_route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    # - 0.0.0.0:53

sniffer:
  enable: false
  # force-dns-mapping: true
  # parse-pure-ip: false
  override-destination: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  force-domain:
    - "+.v2ex.com"
  skip-domain:
  - Mijia Cloud

proxies:
  - name: geph_default
    type: http
    server: 127.0.0.1
    port: 9910
  - name: geph_1
    type: http
    server: 127.0.0.1
    port: 9911
  - name: geph_2
    type: http
    server: 127.0.0.1
    port: 9912
  - name: geph_3
    type: http
    server: 127.0.0.1
    port: 9913
  - name: geph_4
    type: http
    server: 127.0.0.1
    port: 9913

  - name: "WARP"
    type: wireguard
    server: engage.cloudflareclient.com
    port: 2480
    ip: "172.16.0.2/32"
    ipv6: "2606:4700:110:8abe:359b:1b05:fda5:2ca7/128"
    private-key: "EBEM7TfbpXZ2mPv7Y4Wq/ykXOvCBIA4px5OlRqxX8Fc="
    public-key: "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="
    udp: true
    # reserved: [219, 212, 139]
    mtu: 1280
    # dialer-proxy: "WARPOut"
    remote-dns-resolve: true
    dns:
      - https://dns.cloudflare.com/dns-query

mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
secret: touhoured
profile:
  store-selected: true
  store-fake-ip: true

# Meta
inbound-tfo: false # TCP Fast Open
geodata-mode: true
tcp-concurrent: false
unified-delay: false # Self deception
global-client-fingerprint: chrome
external-ui: yacd

geox-url:
  geoip: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat"
  geosite: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat"
  mmdb: "https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
